SELECT DISTINCT 
	YEAR,
	MONTH,
	ITEM_TYPE,
	SUM(CAST(WAREHOUSE_SALES AS DECIMAL(10,2))) Sum_of_sales
FROM dbo.Warehouse_and_Retail_Sales
WHERE ITEM_TYPE NOT IN ('DUNNAGE' , 'REF') -- Materia³y Zwrotne
AND WAREHOUSE_SALES > 0 
GROUP BY YEAR, MONTH, ITEM_TYPE
ORDER BY YEAR, MONTH, ITEM_TYPE


